title: Dennis Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Dennis"
  email: "d.feldbusch@web.de"
  url: "https://www.github.com/DennisFeldbusch"

baseurl: 

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: /_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/references"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Dennis"
year : "2022"
